"""add price to item

Revision ID: 1f25f6c321c7
Revises: 3433a625235d
Create Date: 2024-03-14 21:45:02.219587

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f25f6c321c7'
down_revision: Union[str, None] = '3433a625235d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('price', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item', 'price')
    # ### end Alembic commands ###
